### ISSUE TITLE
Missing blocking pop-up for inline buttons

### ISSUE THREAD

**Issue by ivosturm** [Andries-Smit/DataGridExtention#12]
Hi Andries,

For a customer we use this widget extensively with large datasets and heavy microflows. Since the inline-buttons are missing a blocking pop-up feature, sometimes users trigger the logic multiple times, thinking nothing is happening. Can you change the triggering of the microflow to:

				mx.ui.action(microflow,{
					params:	{
						applyto: 'selection',
						guids: [rowObject.getGuid()]
					},
					progress: "modal",
					origin: this.mxform,
					callback: function() {
						   
					},
					error: function(e) {
						logger.error("DataGridExtension.widget.InlineButtonsn.onclickEventInline: XAS error executing microflow" + e);
					}					
				},this);

            

So a blocking popup is triggered. The above code is working in my local copy of the widget.

Regards,
Ivo

**Comment by Andries-Smit** [comment]
Thanks Ivo, will be in the next release

**Comment by Andries-Smit** [comment]
released: https://appstore.home.mendix.com/link/app/877/Flock-of-Birds/Data-Grid-Extension-(Flex-Headers)
