### ISSUE TITLE
Uncaught exception when sortParams variable is empty in FlexColumns.js

### ISSUE THREAD

**Issue by ivosturm** [Andries-Smit/DataGridExtention#13]
Hi Andries,

When implementing the flex headers feature, I ran into an issue as stated in the title of this issue. I added the following in the FlexColumns.js starting from line 104

// 20170117 - Ivo Sturm - Added && sortParams, since sortParams can be undefined and .length gives an undefined error
                        if(sortable && sortParams ){
                            for (var j = 0; j < sortParams.length; j++) {
                                if (sortParams[j][0] === this.gridAttributes[i].tag)
                                    this.gridAttributes[i].sort = sortParams[j][1];
                            }
                        }

**Comment by Andries-Smit** [comment]
thanks. will be in the next release

**Comment by Andries-Smit** [comment]
released: https://appstore.home.mendix.com/link/app/877/Flock-of-Birds/Data-Grid-Extension-(Flex-Headers)
