### ISSUE TITLE
Enabling Paging Button hiding causes error in 6.10.3

### ISSUE THREAD

**Issue by tieniber** [Andries-Smit/DataGridExtention#14]
Looks like lines 44 and 47 throw errors in Mendix 6.10.3 when you enable paging button hiding:

https://github.com/Andries-Smit/DataGridExtention/blob/master/src/DataGridExtension/widget/PagingButtons.js#L44

https://github.com/Andries-Smit/DataGridExtention/blob/master/src/DataGridExtension/widget/PagingButtons.js#L47

These lines reference the 9th child (childNodes[8]) of the paging toolbar, but there are only 6 elements in a Mendix 6.10.3 grid.

Disabling this option allows the widget to work.

**Comment by Andries-Smit** [comment]
Thanks for the pull request. Fix will be in the next release.
Though gulp will be replaced by grunt

**Comment by Andries-Smit** [comment]
released: https://appstore.home.mendix.com/link/app/877/Flock-of-Birds/Data-Grid-Extension-(Flex-Headers)
