### ISSUE TITLE
In Mx 5.12 the unusable buttons hiding does not work any more for a template grid.

### ISSUE THREAD

**Issue by rik-bos** [Andries-Smit/DataGridExtention#4]
Hi there,

I often use the Data Grid Extension for templategrids and I like it. However since the update to the newer Mx versions, the Unusable Buttons hiding (tab Toolbar) does not work any more. Maybe the js API has changed here as well.

Can you fix this?

Thanks in advance!

**Comment by Andries-Smit** [comment]
Hi Rik,

Did you also test with the version from the github? 

The app store was broken and can not connect the repository nor upload a file....
But this time i managed (this time) to upload a new file, when Mendix approves it show up in the app store.

For now you can use the [https://github.com/Andries-Smit/DataGridExtention/releases/tag/2.4](https://github.com/Andries-Smit/DataGridExtention/releases/tag/2.4)

Cheers,
Andries

**Comment by rik-bos** [comment]
I thought so, bit I will retry that.

**Comment by rik-bos** [comment]
It is indeed also with the Github version. The page cannot be loaded and
the loading indicator keeps spinning.

Met vriendelijke groet,

Rik Bos BSc LL.B
Technisch Directeur

*LIFTINZICHT*

Dinkel 5
3068 HB  Rotterdam
tel:          085 - 877 94 67
*mob:       06 - 249 34 712*
e-mail:    r.bos@liftinzicht.nl
Internet:  www.liftinzicht.nl

2015-02-14 13:24 GMT+01:00 <r.bos@liftinzicht.nl>:

**Comment by Andries-Smit** [comment]
As you say, using the data grid extension for template grids... unsupported
feature so far.
So i created a test case in the project and added a fix.
Please check if this solves your problem to
https://github.com/Andries-Smit/DataGridExtention/blob/master/test/widgets/DataGridExtension.mpk


2015-02-16 16:13 GMT+01:00 Rik Bos <notifications@github.com>:

**Comment by rik-bos** [comment]
It works!

Met vriendelijke groet,

Rik Bos BSc LL.B
Technisch Directeur

*LIFTINZICHT*

Dinkel 5
3068 HB  Rotterdam
tel:          085 - 877 94 67
*mob:       06 - 249 34 712*
e-mail:    r.bos@liftinzicht.nl
Internet:  www.liftinzicht.nl

2015-02-16 20:49 GMT+01:00 Andries Smit <notifications@github.com>:
