### ISSUE TITLE
I am unable to see dashboard/loginpage after adding DatagridExtenion

### ISSUE THREAD

**Issue by srinivas1918** [Andries-Smit/DataGridExtention#9]
I am trying add DataGridExtention for showing Link in one particular column of dataTable. I am unable to see Login page after adding this widget

PFA..
![capture](https://cloud.githubusercontent.com/assets/10140620/17021827/1ba56648-4f68-11e6-9378-52a4b55f3af4.JPG)

**Comment by JelteMX** [comment]
This issue is a duplicate of #7

**Comment by Andries-Smit** [comment]
released: https://appstore.home.mendix.com/link/app/877/Flock-of-Birds/Data-Grid-Extension-(Flex-Headers)
